GROUPS.push(
{
    id: 'rfid-readers',
    name: 'RFID Readers',
    blurb:
      'Registry/CRUD for physical RFID hardware (iData flatbed scanners, handhelds, fixed dock/gate readers). ' +
      'Tracks identity, network address and operational status.',
    endpoints: [
      {
        id: 'create-reader',
        method: 'POST',
        path: '/rfid-readers',
        title: 'Register reader',
        status: 'implemented',
        auth: true,
        source: 'src/modules/rfid-readers/rfid-readers.controller.ts',
        description: 'Registers a new RFID reader. serialNumber must be unique. Defaults status to ACTIVE.',
        requestBody: {
          contentType: 'application/json',
          fields: [
            { name: 'name', type: 'string', required: true, description: 'Display name. Max 120.' },
            { name: 'serialNumber', type: 'string', required: true, description: 'Unique hardware serial. Max 100.' },
            { name: 'model', type: 'string', required: false, description: 'Hardware model. Max 120.' },
            { name: 'ipAddress', type: 'string (IP)', required: false, description: 'IPv4/IPv6 address.' },
            { name: 'status', type: 'enum(ACTIVE|INACTIVE|MAINTENANCE)', required: false, description: 'Defaults to ACTIVE.' },
            { name: 'notes', type: 'string', required: false, description: 'Free text. Max 500.' },
          ],
          sample: {
            name: 'Store 014 Checkout 2 Flatbed',
            serialNumber: 'IDATA-A500-014-02',
            model: 'iData A500',
            ipAddress: '10.14.2.21',
            status: 'ACTIVE',
            notes: 'USB to POS terminal 2',
          },
        },
        responses: [
          {
            status: 201,
            description: 'Reader created.',
            sample: {
              statusCode: 201,
              message: 'Success',
              data: {
                id: 'b1d9f4a2-3c5e-4f8a-9b1c-2d3e4f5a6b7c',
                name: 'Store 014 Checkout 2 Flatbed',
                serialNumber: 'IDATA-A500-014-02',
                model: 'iData A500',
                ipAddress: '10.14.2.21',
                status: 'ACTIVE',
                notes: 'USB to POS terminal 2',
                createdAt: '2026-06-24T09:00:00.000Z',
                updatedAt: '2026-06-24T09:00:00.000Z',
              },
            },
          },
        ],
        errors: [
          { status: 400, code: 'BadRequest', when: 'Validation failure (e.g. invalid IP, missing name/serial).' },
          { status: 409, code: 'Conflict', when: 'serialNumber already registered (unique constraint).' },
        ],
      },
      {
        id: 'list-readers',
        method: 'GET',
        path: '/rfid-readers',
        title: 'List readers',
        status: 'implemented',
        auth: true,
        source: 'src/modules/rfid-readers/rfid-readers.controller.ts',
        description: 'Lists all readers, optionally filtered by status.',
        queryParams: [
          { name: 'status', type: 'enum(ACTIVE|INACTIVE|MAINTENANCE)', required: false, description: 'Filter by operational status.' },
        ],
        responses: [
          {
            status: 200,
            description: 'Array of readers.',
            sample: {
              statusCode: 200,
              message: 'Success',
              data: [
                {
                  id: 'b1d9f4a2-3c5e-4f8a-9b1c-2d3e4f5a6b7c',
                  name: 'Store 014 Checkout 2 Flatbed',
                  serialNumber: 'IDATA-A500-014-02',
                  model: 'iData A500',
                  ipAddress: '10.14.2.21',
                  status: 'ACTIVE',
                  notes: 'USB to POS terminal 2',
                  createdAt: '2026-06-24T09:00:00.000Z',
                  updatedAt: '2026-06-24T09:00:00.000Z',
                },
              ],
            },
          },
        ],
        errors: [{ status: 400, code: 'BadRequest', when: 'status is not a valid enum value.' }],
      },
      {
        id: 'get-reader',
        method: 'GET',
        path: '/rfid-readers/:id',
        title: 'Get reader',
        status: 'implemented',
        auth: true,
        source: 'src/modules/rfid-readers/rfid-readers.controller.ts',
        description: 'Fetches a single reader by id.',
        pathParams: [{ name: 'id', type: 'uuid', description: 'Reader id.' }],
        responses: [
          {
            status: 200,
            description: 'Reader.',
            sample: {
              statusCode: 200,
              message: 'Success',
              data: {
                id: 'b1d9f4a2-3c5e-4f8a-9b1c-2d3e4f5a6b7c',
                name: 'Store 014 Checkout 2 Flatbed',
                serialNumber: 'IDATA-A500-014-02',
                model: 'iData A500',
                ipAddress: '10.14.2.21',
                status: 'ACTIVE',
                notes: 'USB to POS terminal 2',
                createdAt: '2026-06-24T09:00:00.000Z',
                updatedAt: '2026-06-24T09:00:00.000Z',
              },
            },
          },
        ],
        errors: [{ status: 404, code: 'NotFound', when: 'No reader with that id.' }],
      },
      {
        id: 'update-reader',
        method: 'PATCH',
        path: '/rfid-readers/:id',
        title: 'Update reader',
        status: 'implemented',
        auth: true,
        source: 'src/modules/rfid-readers/rfid-readers.controller.ts',
        description: 'Partially updates a reader. Any subset of the create fields is accepted.',
        pathParams: [{ name: 'id', type: 'uuid', description: 'Reader id.' }],
        requestBody: {
          contentType: 'application/json',
          fields: [{ name: '(any create field)', type: 'partial', required: false, description: 'Provide only the fields to change.' }],
          sample: { status: 'MAINTENANCE', notes: 'RMA pending, antenna fault' },
        },
        responses: [
          {
            status: 200,
            description: 'Updated reader.',
            sample: {
              statusCode: 200,
              message: 'Success',
              data: {
                id: 'b1d9f4a2-3c5e-4f8a-9b1c-2d3e4f5a6b7c',
                name: 'Store 014 Checkout 2 Flatbed',
                serialNumber: 'IDATA-A500-014-02',
                model: 'iData A500',
                ipAddress: '10.14.2.21',
                status: 'MAINTENANCE',
                notes: 'RMA pending, antenna fault',
                createdAt: '2026-06-24T09:00:00.000Z',
                updatedAt: '2026-06-24T10:12:00.000Z',
              },
            },
          },
        ],
        errors: [
          { status: 400, code: 'BadRequest', when: 'Validation failure.' },
          { status: 404, code: 'NotFound', when: 'No reader with that id.' },
          { status: 409, code: 'Conflict', when: 'Changing serialNumber to one already in use.' },
        ],
      },
      {
        id: 'delete-reader',
        method: 'DELETE',
        path: '/rfid-readers/:id',
        title: 'Delete reader',
        status: 'implemented',
        auth: true,
        source: 'src/modules/rfid-readers/rfid-readers.controller.ts',
        description: 'Removes a reader from the registry.',
        pathParams: [{ name: 'id', type: 'uuid', description: 'Reader id.' }],
        responses: [{ status: 204, description: 'Deleted. Empty body.', sample: null }],
        errors: [{ status: 404, code: 'NotFound', when: 'No reader with that id.' }],
      },
    ],
  }
);
